name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Ставим JDK (Android Gradle Plugin требует 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Даем права на gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Сборка проекта
      - name: Build project
        run: ./gradlew build

      # 5. Запуск unit-тестов
      - name: Run unit tests
        run: ./gradlew test

      # 6. (опционально) Запуск инструментальных тестов
      # нужен Android Emulator или Firebase Test Lab
      # - name: Run Android instrumented tests
      #   run: ./gradlew connectedAndroidTest
